[build-system]
requires = ["setuptools>=49.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=python_starter"
testpaths = [
    "tests",
]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true


[[tool.mypy.overrides]]
ignore_missing_imports = true